## SPAFIT - Small Python Application Freezer/Installer Test ##
| Tool | Win | Mac | Issue |
|------|-----|-----|-------|
| briefcase | :no_entry: Not Supported | :x: FAIL | ['Oct 30 12:38:18 jamesmacbookpro com.apple.xpc.launchd[1] (co.abel.main.368672[35315]): Service exited with abnormal code: 1\n\n', 'Traceback (most recent call last):\n\n', '  File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/python/lib/python3.5/runpy.py", line 184, in _run_module_as_main\n\n', '    "__main__", mod_spec)\n\n', '  File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/python/lib/python3.5/runpy.py", line 85, in _run_code\n\n', '    exec(code, run_globals)\n\n', '  File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app/main/app.py", line 6, in <module>\n\n', '    import cryptography.fernet\n\n', '  File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app_packages/cryptography/fernet.py", line 17, in <module>\n\n', '    from cryptography.hazmat.primitives import hashes, padding\n\n', '  File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app_packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>\n\n', '    from cryptography.hazmat.bindings._padding import lib\n\n', "ImportError: No module named '_cffi_backend'\n\n"] |
| cx_freeze | :x: FAIL | :x: FAIL | ['\n\n', '# *** Python 3.5 ***\n\n', '\n\n', '    Win32GUI.c\n\n', '    C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\\users\\james\\projects\\spafit\\test_cx_freeze\\venv\\libs /LIBPATH:c:\\Users\\jame\n\n', 's\\AppData\\Local\\Programs\\Python\\Python35\\libs /LIBPATH:c:\\Users\\james\\AppData\\Local\\Programs\\Python\\Python35 /LIBPATH:c:\\users\\james\\projects\\spafit\\test_cx_freeze\\venv\\PCbuild\\amd64 "/LIBPATH:C:\\Program Files (x86)\\Micr\n\n', 'osoft Visual Studio 14.0\\VC\\LIB\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\LIB\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10586.0\\ucrt\\x64" "/LIBPATH:C:\\Program F\n\n', 'iles (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\lib\\um\\x64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10586.0\\um\\x64" user32.lib build\\temp.win-amd64-3.5\\Release\\source/bases/Win32GUI.obj /OUT:build\\lib.win-amd64-\n\n', '3.5\\cx_Freeze\\bases\\Win32GUI.exe /MANIFEST\n\n', '    Generating code\n\n', '    Finished generating code\n\n', '    running build_scripts\n\n', '    creating build\\scripts-3.5\n\n', '    copying and adjusting cxfreeze -> build\\scripts-3.5\n\n', '    copying and adjusting cxfreeze-quickstart -> build\\scripts-3.5\n\n', "    error: file 'C:\\Users\\james\\AppData\\Local\\Temp\\pip-build-v084ipn9\\cx-freeze\\cxfreeze-postinstall' does not exist\n\n", '\n\n', '    ----------------------------------------\n\n', 'Command "c:\\users\\james\\projects\\spafit\\test_cx_freeze\\venv\\scripts\\python.exe -u -c "import setuptools, tokenize;__file__=\'C:\\\\Users\\\\james\\\\AppData\\\\Local\\\\Temp\\\\pip-build-v084ipn9\\\\cx-freeze\\\\setup.py\';exec(compile(ge\n\n', 'tattr(tokenize, \'open\', open)(__file__).read().replace(\'\\r\\n\', \'\\n\'), __file__, \'exec\'))" install --record C:\\Users\\james\\AppData\\Local\\Temp\\pip-cmdndupo-record\\install-record.txt --single-version-externally-managed --co\n\n', 'mpile --install-headers c:\\users\\james\\projects\\spafit\\test_cx_freeze\\venv\\include\\site\\python3.5\\cx-freeze" failed with error code 1 in C:\\Users\\james\\AppData\\Local\\Temp\\pip-build-v084ipn9\\cx-freeze\\\n\n', '\n\n', '\n\n', '# *** Python 3.4 ***\n\n', '\n\n', 'c:\\Users\\james\\projects\\spafit\\test_cx_freeze>venv\\Scripts\\pip3.exe install -U -r requirements.txt\n\n', 'Collecting PyQt5 (from -r requirements.txt (line 1))\n\n', '  Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 1)) (from versions: )\n\n', 'No matching distribution found for PyQt5 (from -r requirements.txt (line 1))\n\n', '\n\n', 'c:\\Users\\james\\projects\\spafit\\test_cx_freeze>\n', "error: [Errno 2] No such file or directory: '/Users/james/projects/spafit/test_cx_freeze_mac/venv/lib/QtCore.framework/Versions/5/QtCore'\n\n"] |
| osnap | :white_check_mark: PASS | :white_check_mark: PASS | [] |
| py2app | :no_entry: Not Supported | :x: FAIL | ['Oct 29 16:16:40 jamesmacbookpro main[12555]: main Error\n\n', 'Oct 29 16:16:40 jamesmacbookpro main[12555]: 2016-10-29 16:16:40.767 main[12555:171326] main Error\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]: Traceback (most recent call last):\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module>\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:     _run()\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run\n\n', "Oct 29 16:16:42 jamesmacbookpro main[12555]:     exec(compile(source, path, 'exec'), globals(), globals())\n\n", 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/main.py", line 4, in <module>\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:     from PyQt5.QtWidgets import QApplication, QLabel\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "PyQt5/QtWidgets.pyc", line 14, in <module>\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "PyQt5/QtWidgets.pyc", line 10, in __load\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "imp.pyc", line 342, in load_dynamic\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]: ImportError: dlopen(/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   Referenced from: /Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so\n\n', 'Oct 29 16:16:42 jamesmacbookpro main[12555]:   Reason: image not found\n\n', 'Oct 30 12:48:33 jamesmacbookpro main[46379]: main Error\n\n', 'Oct 30 12:48:33 jamesmacbookpro main[46379]: 2016-10-30 12:48:33.404 main[46379:614753] main Error\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]: Traceback (most recent call last):\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module>\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:     _run()\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run\n\n', "Oct 30 12:50:51 jamesmacbookpro main[46379]:     exec(compile(source, path, 'exec'), globals(), globals())\n\n", 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/main.py", line 4, in <module>\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:     from PyQt5.QtWidgets import QApplication, QLabel\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 14, in <module>\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 10, in __load\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "imp.pyc", line 342, in load_dynamic\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]: ImportError: dlopen(/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   Referenced from: /Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so\n\n', 'Oct 30 12:50:51 jamesmacbookpro main[46379]:   Reason: image not found\n\n'] |
| py2exe | :x: FAIL | :no_entry: Not Supported | ['running py2exe\n\n', '\n\n', '  4 missing Modules                  \n\n', '  ------------------                 \n\n', '? pkg_resources.extern.appdirs        imported from pkg_resources\n\n', '? pkg_resources.extern.packaging      imported from pkg_resources\n\n', '? pkg_resources.extern.six            imported from pkg_resources\n\n', '? readline                            imported from cmd, code, pdb\n\n', "Building 'dist\\main.exe'.\n\n", "error: [Errno 2] No such file or directory: 'c:\\\\Users\\\\james\\\\projects\\\\spafit\\\\test_py2exe\\\\venv\\\\lib\\\\site-packages\\\\py2exe\\\\run_w-py3.5-win-amd64.exe'\n", 'Traceback (most recent call last):\n\n', '  File "main.py", line 4, in <module>\n\n', '  File "c:\\python34\\lib\\site-packages\\zipextimporter.py", line 109, in load_module\n\n', '    self.get_data)\n\n', "ImportError: No module named 'sip'\n\n"] |
| pyinstaller | :x: FAIL | :x: FAIL | ['Traceback (most recent call last):\n\n', '  File "lib\\site-packages\\PyInstaller\\loader\\rthooks\\pyi_rth_qt5plugins.py", line 46, in <module>\n\n', '  File "c:\\users\\james\\projects\\spafit\\test_pyinstaller\\venv\\lib\\site-packages\\PyInstaller\\loader\\pyimod03_importers.py", line 573, in load_module\n\n', '    module = loader.load_module(fullname)\n\n', 'ImportError: DLL load failed: The specified procedure could not be found.\n\n', 'PyInstaller Bootloader 3.x\n\n', 'Failed to execute script pyi_rth_qt5plugins\n\n', '\n\n', '2547 INFO: Processing pre-safe import module hook   win32com\n\n', 'Traceback (most recent call last):\n\n', '  File "<string>", line 2, in <module>\n\n', "ImportError: No module named 'win32com'\n\n", '2590 INFO: Processing pre-safe import module hook   win32com\n\n', 'Traceback (most recent call last):\n\n', '  File "<string>", line 2, in <module>\n\n', "ImportError: No module named 'win32com'\n\n", '2630 INFO: Processing pre-safe import module hook   win32com\n\n', 'Traceback (most recent call last):\n\n', '  File "<string>", line 2, in <module>\n\n', "ImportError: No module named 'win32com'\n\n", '2670 INFO: Processing pre-safe import module hook   win32com\n\n', 'Traceback (most recent call last):\n\n', '  File "<string>", line 2, in <module>\n\n', "ImportError: No module named 'win32com'\n\n", '\n\n', '3507 INFO: Looking for dynamic libraries\n\n', '3509 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)\n\n', '3509 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)\n\n', '3509 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)\n\n', '3509 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)\n\n', '3511 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)\n\n', '3511 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)\n\n', '3513 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)\n\n', '3513 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)\n\n', '3515 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)\n\n', '3515 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)\n\n', '3515 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)\n\n', '3517 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)\n\n', '3517 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)\n\n', '3519 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)\n\n', '3519 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)\n\n', '3520 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)\n\n', '3521 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)\n\n', '3522 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqdds.dylib)\n\n', '3522 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqdds.dylib)\n\n', '3524 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)\n\n', '3524 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)\n\n', '3524 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)\n\n', '3524 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)\n\n', '3528 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)\n\n', '3528 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)\n\n', '3528 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)\n\n', '3528 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)\n\n', '3528 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)\n\n', '3530 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)\n\n', '3530 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)\n\n', '3532 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)\n\n', '3532 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)\n\n', '3532 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)\n\n', '3534 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)\n\n', '3534 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)\n\n', '3535 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)\n\n', '3538 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)\n\n', '3538 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)\n\n', '3541 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)\n\n', '3541 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)\n\n', '3541 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)\n\n', '3541 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)\n\n', '3543 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)\n\n', '3543 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)\n\n', '3546 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtCore.so)\n\n', '3550 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)\n\n', '3550 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)\n\n', '3550 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)\n\n', '3550 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)\n\n', '3553 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtGui.so)\n\n', '3553 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtGui.so)\n\n', '3656 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtWidgets.so)\n\n', '3657 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtWidgets.so)\n\n', '3657 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtWidgets.so)\n\n', '3661 INFO: Looking for eggs\n\n', '3661 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.5/Python\n\n', '3677 INFO: Warnings written to /Users/james/projects/spafit/test_pyinstaller_mac/build/main/warnmain.txt\n\n', '\n\n'] |
| pynsist | :white_check_mark: PASS | :no_entry: Not Supported | [] |

Notes
- Generally tried to use Python 3.5.  If a tool failed with 3.5 I tried 3.4.  However, no tool that failed on 3.5 then passed on 3.4.
    
