Oct 30 12:48:33 jamesmacbookpro main[46379]: main Error
Oct 30 12:48:33 jamesmacbookpro main[46379]: 2016-10-30 12:48:33.404 main[46379:614753] main Error
Oct 30 12:50:51 jamesmacbookpro main[46379]: Traceback (most recent call last):
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module>
Oct 30 12:50:51 jamesmacbookpro main[46379]:     _run()
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run
Oct 30 12:50:51 jamesmacbookpro main[46379]:     exec(compile(source, path, 'exec'), globals(), globals())
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/main.py", line 4, in <module>
Oct 30 12:50:51 jamesmacbookpro main[46379]:     from PyQt5.QtWidgets import QApplication, QLabel
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 14, in <module>
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 10, in __load
Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "imp.pyc", line 342, in load_dynamic
Oct 30 12:50:51 jamesmacbookpro main[46379]: ImportError: dlopen(/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
Oct 30 12:50:51 jamesmacbookpro main[46379]:   Referenced from: /Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so
Oct 30 12:50:51 jamesmacbookpro main[46379]:   Reason: image not found
